-- Create table for storing beer types/products
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table products enable row level security;

-- Policies
-- 1. Everyone can view products
create policy "Public read access" 
  on products for select 
  using (true);

-- 2. Only authenticated users can insert/update/delete (Adjust if you need strict roles like 'OWNER')
create policy "Authenticated full access" 
  on products for all 
  using (auth.role() = 'authenticated');
